-- DROP TABLE IF EXISTS SCHOOLCHILD;
-- DROP TABLE IF EXISTS GRADE;
-- DROP TABLE IF EXISTS SCHOOL;
-- DROP TABLE IF EXISTS SCHOOL_GRADE;
--
-- CREATE TABLE SCHOOL (
--     ID INT AUTO_INCREMENT NOT NULL,
--     ADDRESS VARCHAR(255) NOT NULL UNIQUE,
--     SCHOOL_NUMBER INT NOT NULL UNIQUE,
--     CONSTRAINT PK_SCHOOL_ID PRIMARY KEY (ID)
-- );
--
-- CREATE TABLE GRADE (
--     ID INT AUTO_INCREMENT NOT NULL,
--     NAME VARCHAR(3) NOT NULL,
--     CONSTRAINT PK_GRADE_ID PRIMARY KEY (ID)
-- );
--
-- CREATE TABLE SCHOOLCHILD (
--     ID INT AUTO_INCREMENT NOT NULL,
--     FIRST_NAME VARCHAR(255) NOT NULL,
--     AGE INT NOT NULL
--     CONSTRAINT PK_SCHOOLCHILD_ID PRIMARY KEY (ID)
-- );
--
-- CREATE TABLE SCHOOL_GRADE (
--     SCHOOL_ID INT,
--     GRADE_ID INT,
--     CONSTRAINT PK_SCHOOL_GRADE_ID PRIMARY KEY (SCHOOL_ID, GRADE_ID),
--     CONSTRAINT FK_SCHOOL_ID FOREIGN KEY (SCHOOL_ID) REFERENCES SCHOOL(ID),
--     CONSTRAINT FK_GRADE_ID FOREIGN KEY (GRADE_ID) REFERENCES GRADE(ID)
-- );

INSERT INTO SCHOOL (ID, ADDRESS, SCHOOL_NUMBER)
VALUES (1, 'Saint-Petersburg', 123);
INSERT INTO SCHOOL (ID, ADDRESS, SCHOOL_NUMBER)
VALUES (2, 'Moscow', 99)

INSERT INTO GRADE (ID, NAME) VALUES (1, '1A');
INSERT INTO GRADE (ID, NAME) VALUES (2, '2B');
INSERT INTO GRADE (ID, NAME) VALUES (3, '1B');

INSERT INTO SCHOOL_GRADE (SCHOOL_ID, GRADE_ID)
VALUES (1, 1);
INSERT INTO SCHOOL_GRADE (SCHOOL_ID, GRADE_ID)
VALUES (1, 2);
INSERT INTO SCHOOL_GRADE (SCHOOL_ID, GRADE_ID)
VALUES (2, 3);

INSERT INTO SCHOOLCHILD (FIRST_NAME, AGE)
VALUES ('Adam', 33);
INSERT INTO SCHOOLCHILD (FIRST_NAME, AGE)
VALUES ('Olivia', 99);
INSERT INTO SCHOOLCHILD (FIRST_NAME, AGE)
VALUES ('Bob', 15);