-- DROP TABLE IF EXIST AUTHOR;
-- DROP TABLE IF EXIST ACCOUNT;
-- DROP SEQUENCE SEQ_AUTHOR_ID;

-- CREATE SEQUENCE SEQ_AUTHOR_ID START WITH 1 INCREMENT BY 1;
-- CREATE TABLE AUTHOR (
--     ID           NUMBER(19,0) DEFAULT SEQ_AUTHOR_ID.NEXTVAL NOT NULL,
--     FULLNAME     VARCHAR(50) NOT NULL UNIQUE,
--     CONSTRAINT PK_AUTHOR_ID PRIMARY KEY (ID)
-- );


-- CREATE TABLE ACCOUNT (
--     ACC_ID   NUMBER(19,0) NOT NULL,
--     LOGIN    VARCHAR(25) NOT NULL UNIQUE,
--     CONSTRAINT PK_AUTHOR_ID PRIMARY KEY (ACC_ID),
--     CONSTRAINT FK_AUTHOR_ID FOREIGN KEY(ACC_ID) REFERENCES AUTHOR(ID)
-- );

-- select * from AUTHOR;
-- select * from ACCOUNT;

--
-- alter table ACCOUNT disable constraint FK_ACCOUNT_ID;
-- truncate table AUTHOR;
-- truncate table  ACCOUNT;
-- alter table ACCOUNT enable constraint FK_ACCOUNT_ID;
-- commit;
--